plugins = []
headers = []
redirects = []

[functions]

  [functions."*"]

[build]
base = "/Users/imac/Downloads/mern-social-media-master"

  [build.environment]

  [build.processing]

    [build.processing.css]

    [build.processing.html]

    [build.processing.images]

    [build.processing.js]

  [build.services]